### ISSUE TITLE
Add PayPal

### ISSUE THREAD

**Issue by 1442acb42ee0e3a727d7330e9755eb94** [adyen-examples/adyen-java-spring-online-payments#1]
This is a feature request: Could you please add PayPal as a means of payment to the spring boot example app?

**Comment by deepu105** [comment]
Thanks for the request. We will consider this based on our priorities. Please note that code wise adding paypal should be quite straightforward as you can replicate Ideal and change some configurations to get paypal working, but the biggest part is configuring  your paypal account itself and setting it up in the Adyen customer area see this: https://docs.adyen.com/payment-methods/paypal/web-component

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
Thanks for the prompt feedback. I think people are interested in how adyen integrates PayPal. I know that we can implement this on our own, but I was hoping to find a ready demo. We are currently using stripe and are considering to add PayPal OR to switch altogether to adyen. Because of that it would have been good to find an example/demo, which illustrates how one can integrate Credit Card Payment and PayPal at the same time.

**Comment by deepu105** [comment]
Thanks for the feedback. We will try to add a demo to this app soon

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
That would be great! This will help companies who would like to use Credit Card + PayPal to make a decision in favor of adyen.

**Comment by deepu105** [comment]
done via https://github.com/adyen-examples/adyen-java-spring-online-payments/commit/caf8a526e3ca9eedb0ad3a4b830aa33b44e6ca46
