### ISSUE TITLE
 CORS problem

### ISSUE THREAD

**Issue by YongMingMao** [adyen-examples/adyen-java-spring-online-payments#10]
when I use drop-in ,I click the  <continue to checkout> button ，the page shows that "Error! Please review response in console and refer to Response handling."
by watching the console, I find out it is a  CORS problem. 
how to solve this problem
thanks
<img width="635" alt="微信图片_20211221150309" src="https://user-images.githubusercontent.com/48505397/146886243-1ee65ee2-8395-4e89-94e0-a3cad016e55a.png">
<img width="621" alt="微信图片_202112211503091" src="https://user-images.githubusercontent.com/48505397/146886246-273ff09a-895a-49f3-8c60-f8d9aabd0f48.png">
<img width="698" alt="微信图片_202112211503092" src="https://user-images.githubusercontent.com/48505397/146886247-7c927032-18d4-400f-8e91-1810a8862a04.png">

**Comment by gcatanese** [comment]
@YongMingMao It appears to be a configuration problem: in the "Customer Area" add the URL of your application (`http://localhost:8080`) in the Allowed Origin list, see [Manage Allowed Origins](https://docs.adyen.com/development-resources/client-side-authentication#allowed-origins) which is necessary to authorize the domains/hostnames performing client requests.

Let me know if it helps (or not).

**Comment by gcatanese** [comment]
@YongMingMao I am closing this now. If the solution above didn't help please get in touch with us so we can explore/help
