### ISSUE TITLE
HTTP status Response - unauthorized [Solved]

### ISSUE THREAD

**Issue by taeyon998** [adyen-examples/adyen-java-spring-online-payments#11]
Problem: There is an error while trying your example code. I believe the problem is with "HTTP status Response - unauthorized," but I thought I provided the correct credentials (API key and merchant account).

![image](https://user-images.githubusercontent.com/65479405/148376793-2e7281fa-44d9-40ba-90d5-044e02c74481.png)
![image](https://user-images.githubusercontent.com/65479405/148376799-6007cae0-f31c-48a8-916f-4b2da77ee8f3.png)

![image](https://user-images.githubusercontent.com/65479405/148373811-03322650-ae6a-46e8-9e76-631dccca0b87.png)

Question: It is my problem, and what did I do wrong? (I checked that the API KEY was right and up to date)

The code I ran (+the credentials I provided):
```
export ADYEN_API_KEY="AQEnhmfuXNWTK0Qc+iSEk2EhqOqwQYYaWMKNZHVRhqPO0vSX4EQ1ag5eEMFdWw2+5HzctViMSCJMYAc=-xeNNimObWprWbAPMbwt1eT6ccku8onG4VYRWalj1ftE=-Xgbz;#[7DN8PSWhm"
export ADYEN_MERCHANT_ACCOUNT="TaeyonKim751ECOM"
export ADYEN_CLIENT_KEY="export ADYEN_CLIENT_KEY="test_NBXB77N2HVHZPC2RNQ64IXMT5MJEQQMJ""
./gradlew bootRun

```
Note: The merchant account and API key is from a test account I created. I followed the steps from: https://docs.adyen.com/online-payments/integration-checklist

My Merchant account:
![image](https://user-images.githubusercontent.com/65479405/148377204-594536eb-08da-4676-b83a-732533662fcc.png)

My API key:
![image](https://user-images.githubusercontent.com/65479405/148377136-f271b0db-0025-4221-b2a2-2f5ec3b2e059.png)

My client key:
![image](https://user-images.githubusercontent.com/65479405/148377285-e053a37a-4c74-4b09-94af-62109ee28cb0.png)

I have also added "https://localhost:8080" to the origin of my client key as follows:
![image](https://user-images.githubusercontent.com/65479405/148377006-f238fe4a-b7ae-42c6-930f-ec6fafe34252.png)

Full image of error:
![image](https://user-images.githubusercontent.com/65479405/148373844-d9297db0-818f-4dc2-8ba4-f0397ebf20e6.png)
![image](https://user-images.githubusercontent.com/65479405/148373851-c26e8b83-2a1d-4ecd-89c1-a13757ff60e0.png)
![image](https://user-images.githubusercontent.com/65479405/148373855-3c2fa1ca-99d0-42da-85db-d006e8f871c9.png)

**Comment by taeyon998** [comment]
I solved my own problem by giving API permission to my merchant account, as shown in: https://docs.adyen.com/development-resources/api-credentials#api-permissions

Now it works!

**Comment by gcatanese** [comment]
@taeyon998  Well done, I am closing the issue then.
