### ISSUE TITLE
Gradlew build is throwing exception. 

### ISSUE THREAD

**Issue by anujpradhaan** [adyen-examples/adyen-java-spring-online-payments#2]
**./gradlew build** 

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/anuj/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.13/ac054525fdc81cbd0bc2552b57052ebb1a93cd40/groovy-2.5.13.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**com.adyen.checkout.OnlinePaymentsApplicationTests > contextLoads() FAILED**
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:529
            Caused by: java.lang.IllegalArgumentException at PropertyPlaceholderHelper.java:178

**1 test completed, 1 failed**

As a work around, I had to install gradle separately and build using gradle command to make it work. Please verify it at your end and update the documentation.

**Comment by deepu105** [comment]
what Java version are you using?

**Comment by anujpradhaan** [comment]
Java 11

**Comment by deepu105** [comment]
I think you didn't export the env vars may be, thats the only situation where I can reproduce the issue. Still I dont know how it works with global gradle for you but not the wrapper. Also `./gradlew build` is not required actually. I'll remove it from Readme. Can you export the variables and then just try `./gradlew bootRun`?
```
export ADYEN_API_KEY=yourAdyenApiKey
export ADYEN_MERCHANT_ACCOUNT=yourAdyenMerchantAccount
export ADYEN_CLIENT_KEY=yourAdyenClientKey
```

**Comment by anujpradhaan** [comment]
I am sure I tried this after exporting these fields. I the **solution is to install gradle** and then anyways everything will work. 

I feel you can close this and keep it here just in case someone else encounters the same.

**Comment by deepu105** [comment]
Thats not accurate actually. You don't have to install Gradle. The wrapper
is enough as its the same as installed gradle just a different version.
Probably you have some issue in your environment configuration thats
causing the problem. You can easily verify that by running ./gradlew
bootRun and if it fails with env var not available then there is the issue
