### ISSUE TITLE
Terminal API

### ISSUE THREAD

**Issue by emirmo** [adyen-examples/adyen-java-spring-online-payments#30]
Hi,

Could someone provide a simple Terminal API request and response example?

The Java library itself seems to provide some unit tests using the TerminalAPIRequest and TerminalAPIResponse classes, but it's a little difficult to deduce how to write simple test API calls, similar to payment checkouts.

**Comment by jlengrand** [comment]
Hey there! 

You are correct, so far our samples are very much focused on checkout related capabilities.
I understand you'd like some examples with the [Terminal API](https://docs.adyen.com/point-of-sale/terminal-api).

What would you want to see exactly?
Do you have precise examples you'd like to see ?

**Comment by emirmo** [comment]
Hi, thanks for the response.

I'd be happy with seeing a basic example of an asynchronous call to start a terminal cloud session, and then receiving a webhook response after a terminal card payment has been initialized or completed.

E.g. our backend might remotely (via Adyen) tell the terminal to start a session for paying a specific amount via credit card. The session would then start on the terminal device, and the device would send back notifications (via Adyen) to our backend's webhook when the session starts or ends (or if there is an error/rejection).

While the regular checkout can be performed via test cards or test PayPal accounts, Adyen doesn't seem to support simulated/mock _terminal_ behavior. So in this case, the workflow always needs to be tested directly on the terminal devices. Having a simple example would be helpful for debugging purposes.

If you believe this case doesn't quite fit the purpose of these examples, I can close it, but I think a small piece of code demonstrating a terminal session could be quite helpful.

**Comment by sgaguadero** [comment]
Any update from this topic?. I'm in the same scenario to test terminals with the API.

**Comment by jlengrand** [comment]
Hey there. Apologies, we've been running behind with other activities but this is still on our Radar. Sorry I can't give you a better estimate for now

**Comment by Kwok-he-Chu** [comment]
@sgaguadero @emirmo We've added the integration-example for the cloud terminal api/sync endpoint in #191
